### ISSUE TITLE
Model Setup documentation

### ISSUE THREAD

**Issue by bstabler** [RSGInc/BKRCast#15]
@s-yan - It will be helpful to include a master directory diagram/tree to show how it looks like after set up, perhaps combine this section with the sub-section called “Master Directory”?

**Comment by nsdhakar** [comment]
updated: https://github.com/RSGInc/BKRCast/wiki/BKRCast%20Setup#model-setup

**Comment by nsdhakar** [comment]
Master directory is updated to include directory structure after a model run.
