### ISSUE TITLE
Model Run Settings, provide more detail documentation

### ISSUE THREAD

**Issue by bstabler** [RSGInc/BKRCast#16]
@s-yan 

Model Run Settings, provide more detail documentation of the three configuration files: 
input_configuration.py, 
emme_configuration.py, and 
daysim_configuration_template.properties

  - For each of the files, add an overview section to describe all the major functions the file accomplishes
  - Perhaps combine this section with the sub-section called “Scripts”?
  - Each of the Python file includes some documentation. Somewhere in the model documentation,  please more fully explain the available option choices for each line in the sequence as they appear in the corresponding Python file, what each choice does, and when to select a certain option.

**Comment by nsdhakar** [comment]
Updated the sections of the three files to contain an overview sub-section. Also, added more details to the options (flags) available to a user. @s-yan please review and let us know if you need more information.

**Comment by bstabler** [comment]
@nsdhakar to address @joewildey 's comments

**Comment by nsdhakar** [comment]
Addressed most of @joewildey comments. The comments where some descriptions are missing are still to do. I would be updating those as I keep working on the model.
