### ISSUE TITLE
Inputs documentation

### ISSUE THREAD

**Issue by bstabler** [RSGInc/BKRCast#17]
@s-yan 

  - Land use files: provide updated field definitions for the “parcel file”.
  - Supplemental trip files: explain how and when they are converted from the PSRC’s 4K zone system to the BKR zone system

**Comment by nsdhakar** [comment]
Added the following in supplemental sub-section under inputs:

> While transferring the SoundCast model to BKRCast, the seed supplemental trips were converted from PSRC's 4k zone system to BKR zone system using `psrc2bkr_trips.py` under `psrc_to_bkrcast_scripts`. The conversion is no longer required as the supplemental trips from a previous BKRCast run (outputs/supplemental/[tod].h5) can be used as seed supplemental trips for a new BKRCast run.
