### ISSUE TITLE
Create a Scenario documentation

### ISSUE THREAD

**Issue by bstabler** [RSGInc/BKRCast#18]
@s-yan 

Create a Scenarios: a more thorough review of the Model Setting and Script files will help identify additional scenario types to make this section more complete

**Comment by nsdhakar** [comment]
Added more detail to model settings and scripts. @s-yan please let us know if you have any particular scenario in mind. 
Also, I have added a sub-section on "updating model coefficients" and will be adding a sub-section on "adding/splitting a zone" soon.

**Comment by nsdhakar** [comment]
Addressed most of @joewildey comments. The comments where some descriptions are missing are still to do. I will be adding more scenarios as we keep working on the model.
