### ISSUE TITLE
Python script cannot find other scripts in the working directory

### ISSUE THREAD

**Issue by nsdhakar** [RSGInc/BKRCast#8]
On @Hu's machine, the Python scripts can't find other scripts in the current working directory. This use to work for him and still works for Nagendra and PSRC. Update the scripts by appending the current working directory to all scripts so it works.

**Comment by PeterVermont** [comment]
You really should try to avoid putting in absolute paths.

A better approach is to make paths relative to the location of the script.

Here is what I often use: http://stackoverflow.com/a/4943474/283973
……………………………………………..
PETER ANDREWS
Senior Software Engineer

RSG
55 Railroad Row | White River Junction, VT 05001
o 802.359.6411 | m 802.356.3141
www.rsginc.com<http://www.rsginc.com/>
……………………………………………..
